### ISSUE TITLE
How to explain the number of bits representing Euclidean space from a geometric perspective.

### ISSUE THREAD

**Issue by Qingzhang1994** [yangshengaa/stable-hyperbolic#1]
I am very interested in your work. I would like to know how to prove the radius of Euclidean space. Thank you for your reply.
![image](https://github.com/user-attachments/assets/259d1727-1362-4339-89e8-b4a31725b038)
![image](https://github.com/user-attachments/assets/3c117493-6d01-41c9-bb0d-ab6587ece92c)

**Comment by yangshengaa** [comment]
Hi Qing, Thank you for your interest!

Here the radius means the max scale of feature within which can be represented accurately under the Float64 system. So, for the sake of representation, we believe that Euclidean space is effectively unbounded, at least its radius is orders of magnitude larger than a radius of 38. This is one of the motivations we seek a Euclidean reparametrization for circumventing the Poincaré bounded problem. 

I frankly do not quite get your title exactly: "How to explain the number of bits representing Euclidean space from a geometric perspective". To attempt to answer your question, the most naive pictorially interpretation would be flipping each bit from 0 to 1 in Euclidean space sends this representation from x to 2x. 

Apologies for the slow response, but let me know if you have further questions.

**Comment by Qingzhang1994** [comment]
谢谢您的回复。我对双曲空间的认知还停留在其距离呈指数级增长特性，能够表示层级数据，所以在图像数据中有很好的效果。
